import React from 'react';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';

export const metadata = {
  title: 'Terms & Conditions | Solix Renewable Energy',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-solix-bg flex flex-col justify-between">
      <Header />

      <section className="pt-36 pb-20 px-4 sm:px-8 max-w-4xl mx-auto w-full">
        <div className="bg-white rounded-3xl p-8 sm:p-12 border border-solix-border shadow-solix space-y-6 text-solix-dark">
          <h1 className="text-3xl font-extrabold border-b pb-4">Terms & Conditions</h1>
          <p className="text-xs text-solix-muted">Last Updated: August 6, 2026</p>

          <p className="text-sm leading-relaxed text-solix-muted">
            By accessing or using the Solix platform, websites, or customer portal, you agree to be bound by these Terms and Conditions.
          </p>

          <h3 className="text-lg font-bold">1. Intellectual Property</h3>
          <p className="text-xs text-solix-muted leading-relaxed">
            All content, engineering diagrams, software telemetry code, branding assets, and documentation displayed on this website are the property of Solix Energy Group and protected by international copyright laws.
          </p>

          <h3 className="text-lg font-bold">2. Technical Estimates & Warranties</h3>
          <p className="text-xs text-solix-muted leading-relaxed">
            Provisional energy production forecasts generated by our website forms are for planning purposes. Formal performance guarantees are binding only upon execution of an official Engineering, Procurement, and Construction (EPC) contract.
          </p>
        </div>
      </section>

      <Footer />
    </main>
  );
}
